### ISSUE TITLE
Publishing a Firefox version

### ISSUE THREAD

**Issue by yan12125** [tiratatp/facebook_adblock#1]
Hi tiratatp,

I just found this project. It's quite useful and block things well. It works fine with Firefox, too. I'd like to publish a Firefox version to https://addons.mozilla.org/, can I?

**Comment by tiratatp** [comment]
Hi there! I'm glad you like it.
You could publish to Firefox. As long as you respect the GPL license (e.g. keep it open source), feel free to publish it. :smile: 
If you publish it, let me know so I can put the link here too.

**Comment by yan12125** [comment]
Thanks. Submitted to Mozilla and it's now being reviewed :)

**Comment by yan12125** [comment]
Reviewed ok: https://addons.mozilla.org/en-US/firefox/addon/facebook_adblock/

**Comment by tiratatp** [comment]
Yay! I never publish to Firefox. Is it just my source code or do you have to modify something? If you have to modify something, could you release the source code?

**Comment by yan12125** [comment]
Nothing is modifed. Firefox 48 or newer allows using simple Chrome extensions directly. I just repack it and upload it to addons.mozilla.org with my API key. The XPI file at https://addons.mozilla.org/en-US/firefox/addon/facebook_adblock/ is just a zip file, which contains the same set of files in this project.

**Comment by tiratatp** [comment]
Thanks for the clarification! I'll go ahead and close this issue. Thanks again for publishing this for Firefox!

**Comment by yan12125** [comment]
Hi @tiratatp, I got a legal letter from Adblock Plus lawyers, saying that my Firefox addon violates their trademark rights. I've renamed the Firefox addon to something different. For this upstream project, I guess the safest way is to rename it, too. How do you think?

**Comment by tiratatp** [comment]
This is so stupid. Can you forward me an email?

**Comment by yan12125** [comment]
What's your mail address?
