### ISSUE TITLE
Suggested Posts are back

### ISSUE THREAD

**Issue by dhicks** [tiratatp/facebook_adblock#10]
As the title says.  HTML with an example Suggested Post is attached. (For some reason my XML filter wouldn't clean this up automatically, and it looks like I mismatched some of the <div>s when I was cleaning manually.) 

[suggested post 2017-12-08.html.txt](https://github.com/tiratatp/facebook_adblock/files/1542994/suggested.post.2017-12-08.html.txt)

**Comment by tiratatp** [comment]
Could you try to test it?
When you go to console and enter this,
document.querySelectorAll("span > div > div > a[href='#']:only-child")
does it only select stuff in the suggested post?

**Comment by dhicks** [comment]
Yes, it appears to select just the “Sponsored” text in a Suggested Post.

**Comment by tiratatp** [comment]
Published version 1.3.5

**Comment by yan12125** [comment]
I've uploaded version 1.3.6 for Firefox. Sorry for the delay - I was out of Internet in the past 3 weeks.
