### ISSUE TITLE
[BUG] Sponsored posts showing

### ISSUE THREAD

**Issue by Xenoamor** [tiratatp/facebook_adblock#100]
**Environment**
 - Extension version: 1.9.4
 - Browser and version: Firefox 89.0.2
 - OS and version: Linux Mint 20.1

**Describe the bug**
Sponsored posts are now appearing
![image](https://user-images.githubusercontent.com/7109951/131114360-2fb415e9-13d7-4891-a0f5-83bcee0df621.png)

**Screenshots of console**
![image](https://user-images.githubusercontent.com/7109951/131114443-6b0ea0ea-89cd-4a0d-ac99-dfde4e5386a5.png)

**Comment by Xenoamor** [comment]
This is probably an issue on my side. I refreshed and it's now working again as it should

**Comment by datatypevoid** [comment]
I find that the extension stops working if I go to a different page, group, section etc. I have to constantly reload.
