### ISSUE TITLE
Seeing lots of sponsored posts since I cleared out my browser's cache

### ISSUE THREAD

**Issue by offroadpaparazzi** [tiratatp/facebook_adblock#101]
Chrome 
mac OS ( Big sur)
extension version 1.94

its as if the extension wasn't there any more.

**Comment by offroadpaparazzi** [comment]
No longer working on Mac and PC Firefox and Chrome

**Comment by cbotsikas** [comment]
thank you for your report. I can also see sponsored posts which means that facebook changed the UI. I'll have to check what was changed and how to detect those ads again. Feel free to contribute

**Comment by cbotsikas** [comment]
I'm closing this in favor of #102
