### ISSUE TITLE
[BUG] sponsored posts are back

### ISSUE THREAD

**Issue by VieruTudor** [tiratatp/facebook_adblock#102]
**Environment**
 - Extension version: 1.9.4
 - Browser and version: Chrome Version 94.0.4606.31 (Official Build) beta
 - OS and version: Windows 11

**Describe the bug**
Still showing sponsored posts after running it for a while. It started to show them for 2 days now, after 3 months from installation.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Facebook
2. Scroll down
3. See sponsored posts

** Examples ** 
![image](https://user-images.githubusercontent.com/46691377/132355653-ed2dd8ac-5b09-4291-a6bc-a8c2a8f33f6c.png)
![image](https://user-images.githubusercontent.com/46691377/132355693-eb99d55f-1970-4baf-80b6-915f03fc3115.png)

**Comment by cbotsikas** [comment]
thank you for your report. I can also see sponsored posts which means that facebook changed the UI. I'll have to check what was changed and how to detect those ads again. Feel free to contribute

**Comment by offroadpaparazzi** [comment]
as always, you guys rock!

**Comment by tiratatp** [comment]
Released as 1.9.5 Firefox version was published but Chrome is still in review (up to 4 weeks...)

**Comment by offroadpaparazzi** [comment]
Thank You very much
.

**Comment by Merudo** [comment]
I tried 1.9.5 on both Firefox and Chrome, neither seems to be blocking Sponsored Posts.

**Comment by offroadpaparazzi** [comment]
1.95 works great on Chrome here....thank You

**Comment by cbotsikas** [comment]
> I tried 1.9.5 on both Firefox and Chrome, neither seems to be blocking Sponsored Posts.

@Merudo can you share a screenshot?

> 1.95 works great on Chrome here....thank You

I'm glad it worked for you @offroadpaparazzi.

**Comment by VieruTudor** [comment]
+1, 1.9.5 works on Chrome

**Comment by offroadpaparazzi** [comment]
Seeing them again.....
<img width="751" alt="Screen Shot 2021-09-30 at 9 13 54 AM" src="https://user-images.githubusercontent.com/60391279/135462198-c86394a0-e1ca-4489-9e8c-8a9327eb50e0.png">

**Comment by offroadpaparazzi** [comment]
^^^^^Chrome with 1.95^^^^^

**Comment by cbotsikas** [comment]
> Seeing them again..... <img alt="Screen Shot 2021-09-30 at 9 13 54 AM" width="751" src="https://user-images.githubusercontent.com/60391279/135462198-c86394a0-e1ca-4489-9e8c-8a9327eb50e0.png">

is it a constant issue or after refreshing sponsored posts are gone?

**Comment by offroadpaparazzi** [comment]
Goes away after a refresh.  The one pictured seems to be the one I see whenever I see them.

**Comment by Merudo** [comment]
I tried refreshing in Chrome (Ctrl + F5) but they don't go away:

![image](https://user-images.githubusercontent.com/7371085/135622676-f307ff5f-25d3-4485-aeb5-4311e9d28872.png)
![image](https://user-images.githubusercontent.com/7371085/135622810-8091f65a-40e2-4948-8d62-03c67c6e9d4f.png)
