### ISSUE TITLE
[BUG] Saw a comment that the extension "is also hiding the birthdays panel on the right."

### ISSUE THREAD

**Issue by tiratatp** [tiratatp/facebook_adblock#104]
**Environment**
 - Extension version: 1.9.4
 - Browser and version: [e.g. chrome, safari]
 - OS and version: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**Comment by cbotsikas** [comment]
I don't think there's a birthday panel on fb5 layout. on the right, it's just the contacts for me, even without the plugin. The only way to find the birthdays is to click on the left side, Events -> Birthdays.
![image](https://user-images.githubusercontent.com/1640100/138511933-a76e692d-5145-4fa8-9968-8097924a5766.png)

**Comment by CZeke** [comment]
It's not there all the time -- only on a friend's actual birthday. You even see it for a second before the extension hides it. I for one would definitely appreciate having it unblocked.

**Comment by cbotsikas** [comment]
Thank you @CZeke 
Actually, I just captured one screenshot of it.
![image](https://user-images.githubusercontent.com/1640100/138887824-83b9491f-2d42-48fb-a4b9-6998d92a4668.png)

**Comment by CZeke** [comment]
Thanks! Y'all fixed this just in time for me to catch a birthday today.

**Comment by cbotsikas** [comment]
You're welcome 😁. 
Fixed with version 1.9.6
