### ISSUE TITLE
[BUG] suggested post not hidden

### ISSUE THREAD

**Issue by fpusersuggest** [tiratatp/facebook_adblock#106]
**Environment**
 - Extension version: 1.9.5
 - Browser and version: [e.g. chrome, safari] firefox 92.0
 - OS and version: [e.g. iOS] ubuntu

**Describe the bug**
Suggested post not hidden

**Screenshots of console**
Add screenshots of browser console to help us debugging the problem.
https://imgur.com/a/3iMPxhb

**To Reproduce**
1. Go to '...' just browsing facebook

**Expected behavior**
I just browse facebook

**Additional context**

**Comment by cbotsikas** [comment]
This is not a bug. This plugin doesn't blog suggested posts. 
There's a consideration to add this as an optional feature. see https://github.com/facebook-adblock/facebook_adblock/issues/62
