### ISSUE TITLE
[FEATURE] update permissions to enable add-on for new v3 onion site

### ISSUE THREAD

**Issue by shanghaiscott** [tiratatp/facebook_adblock#108]
**Environment**
 - Extension version: 1.9.5
 - Browser and version:  Tor Browser 11.0 (based on Mozilla Firefox 91.3.0esr) (64-bit)
 - OS and version: MacOS 10.15.7

**Describe the bug**
The add-on is not configured to work on the new v3 onion site:

https://www.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion

**Screenshots of console**

<img width="663" alt="Screen Shot 2021-11-12 at 8 32 32 AM" src="https://user-images.githubusercontent.com/602842/141475286-8beb68e6-ae62-4d35-b8b6-a62ecf90b4e1.png">

**Comment by cbotsikas** [comment]
Looks like Facebook changed the onion domain on May this year. Thanks @shanghaiscott for mentioning it.
The official onion domain can be retrieved by https://www.facebook.com/onion-service which is `facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion` 
More details: https://www.facebook.com/facebookcorewwwi/posts/3727741430665883

**Comment by cbotsikas** [comment]
Version 1.9.6 should be working with onion domain
