### ISSUE TITLE
Malware? Why does this extension require access to the tor darkweb?

### ISSUE THREAD

**Issue by gth001** [tiratatp/facebook_adblock#110]
https://github.com/facebook-adblock/facebook_adblock/search?q=onion

**Comment by gth001** [comment]
Hmm, perhaps it is legitimate. However, Chrome Store has automatically disabled the extension in my browser, alerting me the new permission requirement is mandatory. Uninstalling. https://www.facebook.com/facebookcorewwwi/

**Comment by gth001** [comment]
![image](https://user-images.githubusercontent.com/10224533/142085313-1febf50a-55e9-4db2-9a23-a7225c2655d7.png)

**Comment by cbotsikas** [comment]
Hi @gth001 it's because of the the change on the official onion domain or facebook. This plugin works on both the normal domain as well as the tor domain of facebook. It's not trying to connect to darkweb.
It was requested by https://github.com/facebook-adblock/facebook_adblock/issues/108

**Comment by cbotsikas** [comment]
Here's my comment to your store review:

> It's not malware. Facebook can officially be accessed using a TOR browser. We had to update the onion domain name as it was changed earlier this year. This plugin only works, for your privacy, when you access facebook domain and is not active when you're not on a facebook domain. The change of the domain list triggered the chrome warning. It doesn't try to connect to darkweb; it's not even possible with your regular browser. You are free to review the code and continue our discussion over at github.

Please consider updating your store review, since it's misleading.

**Comment by cbotsikas** [comment]
For your convenience, the related change that triggered the chrome warning was this one: https://github.com/facebook-adblock/facebook_adblock/pull/109/commits/75dc2110bf24bc95fd452b3d3c57760af5b72640 (which is part of https://github.com/facebook-adblock/facebook_adblock/commit/90f697400b976183ad554a8d0f1926461d6bc0ca)
As you can see, we changed the onion domain from the old and deprecated `facebookcorewwwi.onion` to the new `facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion`

**Comment by gth001** [comment]
I'd delete the review but there is no delete or edit button

**Comment by gth001** [comment]
![image](https://user-images.githubusercontent.com/10224533/142095303-20cde24d-6c50-4de5-8e1d-3d661ef713ef.png)
Ill just add a note since it seem you cant edit reviews

**Comment by cbotsikas** [comment]
@gth001 you can edit your message if you click the `Write a review` at the top of your screenshot and then at the bottom, you'll see an edit button

**Comment by cbotsikas** [comment]
Actually, you just need to scroll to the bottom. You'll see the options to Delete or Edit your review.

![image](https://user-images.githubusercontent.com/1640100/142099709-95b07d7b-5f11-4128-99ca-e5aa73a62217.png)

**Comment by gth001** [comment]
ok done
