### ISSUE TITLE
[Feature] Is it possible to hide sponsored pages apearing in feed ?

### ISSUE THREAD

**Issue by diccy** [tiratatp/facebook_adblock#114]
Recently Facebook added other "suggestions" all over the feed :

![image](https://user-images.githubusercontent.com/12190084/155837348-648005b6-854f-4ef3-b69d-e468a3a38cb9.png)

(it's in french, litterally "Suggestions for you")

It looks like this :

![image](https://user-images.githubusercontent.com/12190084/155837429-693be7ac-cff8-4a16-9d59-78c7ce23397f.png)

Can facebook_adblock hide it? Is it planned to do so?

Have a good day everyone :).

**Comment by xavierdubuc** [comment]
Would be really appreciated indeed !

**Comment by cbotsikas** [comment]
Thanks. Handling "suggested for you" content is already a requested feature https://github.com/facebook-adblock/facebook_adblock/issues/62. Those are not considered ads and thus the plugin doesn't hide those by default.
