### ISSUE TITLE
Again block all posts

### ISSUE THREAD

**Issue by GetGankNow** [tiratatp/facebook_adblock#12]
Again block all posts even after the update.
Doesn't block suggestions of friends.

**Comment by GetGankNow** [comment]
Same problem on the Firefox 61.0.2

**Comment by yan12125** [comment]
I can confirm the issue on Firefox 62.0 rc1. Not investigated yet.

**Comment by GetGankNow** [comment]
This block ads : facebook.com###substream_1:has([id^="feed_subtitle_"]:has-text(Sp))

**Comment by dhicks** [comment]
I'm not sure if this is what @GetGankNow means, but for the last couple of days this extension is blogging everything except "People You May Know."  Looking at #11 I'm guessing 1.4.0 was a little too aggressive.  I'd try reverting, but I'm not sure how.  I'm on Chrome 68.0.3440.106.

**Comment by dhicks** [comment]
In case it's helpful, here's a few lines from the console.  I get about 120 lines like this just from loading Fb. 
```
content.js:86 AD Blocked (div > span[data-ft] > div > div) [div#hyperfeed_story_id_5b8a1dae07e830170323044._5jmm._5pat._3lb4.u_287ulanvw]
content.js:86 AD Blocked (div > span[data-ft] > div > div) [div#hyperfeed_story_id_5b8a1dae080cc1161564347._5jmm._5pat._3lb4.u_287ulanvw]
content.js:86 AD Blocked (div > span[data-ft] > div > div) [div#hyperfeed_story_id_5b8a1dae0818a4a50029862._5jmm._5pat._3lb4.u_287ulanvw]
content.js:86 AD Blocked (div > span[data-ft] > div > div) [div#hyperfeed_story_id_5b8a1dae082448987635348._5jmm._5pat._3lb4.u_287ulanvw]
content.js:86 AD Blocked (div > span[data-ft] > div > div) [div#hyperfeed_story_id_5b8a1dae083ea0160790944._5jmm._5pat._3lb4.u_287ulanvw]
```

**Comment by tiratatp** [comment]
I'm out of town at the moment. I'll work on it again on Tuesday.

**Comment by tiratatp** [comment]
I published a new version 1.4.3. Please help test it.

**Comment by yan12125** [comment]
I've uploaded version 1.4.3 to Mozilla. Unwanted stuffs in the sidebar (friend suggestions, etc.) are blocked, while sponsored posts not. The good news is normal posts are back.

**Comment by tiratatp** [comment]
I've updated to 1.4.4 that does not depends on CSS class.

**Comment by yan12125** [comment]
Version 1.4.4 uploaded to Mozilla. It works fine!
