### ISSUE TITLE
[Request] Block Facebook Reel

### ISSUE THREAD

**Issue by Cyanure01** [tiratatp/facebook_adblock#121]
**Environment**
 - Extension version: 1.9.9
 - Browser and version: firefox
 - OS and version: Win10

**Describe the request**
It's very recent here : on computers, Facebook now shows short videos like they did with the app with Reel. As there are no options on facebook to remove it, could facebook-adblock get the ability to block it in near future ? (might it be an option to enable)

**Screenshots of console**
![image](https://user-images.githubusercontent.com/103750487/163569277-136394f8-3f8e-4207-82ff-1442cd8ecce7.png)

**To Reproduce**
Simply refresh the page. Even if you asked to hide previously, it will show you other videos.

**Expected behavior**
Simply block this new content, even through an option.

**Additional context**
/

Thanks for you app and your work ! <3

**Comment by tiratatp** [comment]
Reels are not ads. Reels are short form video.

Like I mentioned earlier, we don't block feature in this extension.
