### ISSUE TITLE
[BUG] ads in my timeline

### ISSUE THREAD

**Issue by Conan179** [tiratatp/facebook_adblock#123]
**Environment**
 - Extension version: 1.9.9 
 - Browser and version: [e.g. chrome, safari] Chrome Version 101.0.4951.54 
 - OS and version: [e.g. iOS] Windows 10

**Describe the bug**
the ads dosont remove.
![fa3_04052022](https://user-images.githubusercontent.com/1906242/166735161-d17918e4-d089-40fa-a065-6bfd1490f97c.JPG)
![fa2_04052022](https://user-images.githubusercontent.com/1906242/166735173-6e473948-3970-4625-9bb0-c93e74793eb1.JPG)
![fa1_04052022](https://user-images.githubusercontent.com/1906242/166735180-6970398e-da10-4737-990f-90d4a76365ac.JPG)

**Comment by cbotsikas** [comment]
Thank you @Conan179 , I'll close this and track the issue on the existing ticket https://github.com/facebook-adblock/facebook_adblock/issues/122

**Comment by Conan179** [comment]
hi, just wanted to let you know that the advertising and the "Sponsored" box at the top right are back.
