### ISSUE TITLE
my normal facebook feeds in my "home" area are blocked in facebook or this facebook adblocker

### ISSUE THREAD

**Issue by walterramjet** [tiratatp/facebook_adblock#13]
using Firefox, the facebook adblock is also blocking my normal feeds from groups I am following.  This started last week, i think.  If I use Chrome, facebook works fine so I went to my addons in Firefox and disabled facebook adblock and now my feeds are coming in like normal. I wonder whats going on?
thanks,
Walt

**Comment by yan12125** [comment]
Sounds like a duplicate of #12

**Comment by tiratatp** [comment]
Duplicate of #12
