### ISSUE TITLE
Block Popular Facebook Videos

### ISSUE THREAD

**Issue by GKid94** [tiratatp/facebook_adblock#14]
Can you please also block the popular Facebook videos

![431231](https://user-images.githubusercontent.com/18757054/45927733-f0459a80-bf37-11e8-990b-34beed496ddd.jpg)

**Comment by tiratatp** [comment]
I think they are okay since they are not paid advertisement.

**Comment by GKid94** [comment]
But it's still a sponsored post

**Comment by tiratatp** [comment]
Are you sure? I didn't see the word "sponsored".

**Comment by GKid94** [comment]
It is since it's showed to all the people who use Facebook, even the ones who don't care about that post

**Comment by tiratatp** [comment]
Sorry that's not the definition of "sponsored". Sponsored means someone
paid Facebook to promote it.

**Comment by GKid94** [comment]
They did since Facebook is spamming the posts to all users
