### ISSUE TITLE
Normal posts in some groups are blocked (Firefox)

### ISSUE THREAD

**Issue by yan12125** [tiratatp/facebook_adblock#18]
Normal posts in one of my private group is blocked. The victim triggers the rule `h5 + [id*="feed_subtitle"] span[role="presentation"]`. Here's a screenshot of partial DOM tree of the victim post:

![default](https://user-images.githubusercontent.com/1937689/49359695-e13a5000-f711-11e8-9f4e-5511e2a95761.png)

I don't find similar issues in other groups, though.

**Comment by tiratatp** [comment]
I think with 1.4.11 should fix this. Can you confirm?

**Comment by yan12125** [comment]
Yes this is fixed! I've uploaded 1.4.12 to Mozilla, too. Sorry for the delay - I was on Chinese New Year vacation last week :)
