### ISSUE TITLE
Extension doesn't work anymore on Chrome Version 72.0.3626.81

### ISSUE THREAD

**Issue by swittenberger** [tiratatp/facebook_adblock#20]
When loading FB on this version of Chrome nothing will load in the feed.
http://prntscr.com/mfyadb

**Comment by tiratatp** [comment]
Can you open developer console and copy the log messages?

**Comment by Stormalong** [comment]
I also encountered this. Console output:

Monitoring Array(1)
ZlC1WF904hQ.js:299 
Stop!
ZlC1WF904hQ.js:299 
This is a browser feature intended for developers. If someone told you to copy-paste something here to enable a Facebook feature or "hack" someone's account, it is a scam and will give them access to your Facebook account.
ZlC1WF904hQ.js:299 
See https://www.facebook.com/selfxss for more information.
ZlC1WF904hQ.js:299 

ZlC1WF904hQ.js:55 ErrorUtils caught an error: "<![EX[["Could not find element \"%s\"%s from module \"%s\"","u_ps_0_0_11","",...". Subsequent errors won't be logged; see https://fburl.com/debugjs.
reportError @ ZlC1WF904hQ.js:55
CiZIFOxmWsj.js:466 Network quality values are overridden using a holdback experiment, and so may be inaccurate
addCommonValues @ CiZIFOxmWsj.js:466

Amusingly the "Stop!" appears in giant red text.

**Comment by tiratatp** [comment]
It doesn't look like my extension is removing anything. Is there anything
else in the log?

**Comment by tiratatp** [comment]
This should be fixed in 1.4.11
