### ISSUE TITLE
Block "Similar to Posts You've Interacted With"

### ISSUE THREAD

**Issue by daemonpun** [tiratatp/facebook_adblock#22]
Could u add this new type of ad, which is essentially trying to push other pages onto you. Please add it to the pile.

**Comment by daemonpun** [comment]
Also this is just a theory, but i think there an event listener on their ads/push crap/sponsored bs that checks to see if u seen their ad, then it edits the code to promote more of that bypassing the blockers. just a theory

**Comment by tiratatp** [comment]
I'll look into the "Similar to Posts You've Interacted With". I don't think I've seen it yet.

I don't think Facebook knows that you have blocked ads since the extension does not block the network request of the ads.
