### ISSUE TITLE
Needs updating. its not working anymore. 

### ISSUE THREAD

**Issue by daemonpun** [tiratatp/facebook_adblock#24]
chrome 72.0.3626.109  stopped working with feed ads. There are so many ads in feed. 
I'd also like to help. I have a MS in CS and worked with HTML and javascript. Jquery not so much.

**Comment by tiratatp** [comment]
You can try to fix it yourself, and then it locally, and then submit a pull
request.
--
Tiratat Patana-anake

**Comment by tiratatp** [comment]
Fixed in 1.4.13
