### ISSUE TITLE
New "Sponsored" layout

### ISSUE THREAD

**Issue by yan12125** [tiratatp/facebook_adblock#25]
Facebook developers are creative. It's a pity to say that but I must face the truth.

![image](https://user-images.githubusercontent.com/1937689/53393272-e1777e00-39d6-11e9-978b-9431293ff536.png)

PS: Cropped from English version of Facebook.

**Comment by tiratatp** [comment]
Hi Chih-Hsuan,

The 1.5.0 should work with this right?

**Comment by tiratatp** [comment]
https://github.com/tiratatp/facebook_adblock/blob/10f62270f8953951e6248b1a33aeef45a72b22b0/content.js#L106 recursively goes into each child and get the visible text.

**Comment by yan12125** [comment]
I'm using 1.5.0. Let me check if there's version mismatch in the Firefox addon.

**Comment by yan12125** [comment]
Looks like the problem is in the blacklist. None of the four blacklist filters (https://github.com/tiratatp/facebook_adblock/blob/master/content.js#L70) appears in the Firefox version of Facebook.

**Comment by tiratatp** [comment]
Blacklist are not being used anymore. It should fall back to
https://github.com/tiratatp/facebook_adblock/blob/master/content.js#L149

Maybe this does not work, div[id^="feed_sub_title"] > :first-child

**Comment by yan12125** [comment]
This issue seems to have disappeared in version 1.6.1. By the way, I've uploaded 1.6.1 to the Mozilla website.
