### ISSUE TITLE
Use native DOM instead of jquery and underscore

### ISSUE THREAD

**Issue by yan12125** [tiratatp/facebook_adblock#3]
Today I got the review feedback for the Firefox version:

> Addon has 9 lines of code. It also included 2 huge libraries for those 9 lines of code. Suggestion: With small/minor changes to code using pure JavaScript, addon would no longer need additional libraries (ie JQuery etc) which improves its performance and efficiency.

Maybe I can have a look (if I'm not lazy :)

**Comment by tiratatp** [comment]
I think native dom access doesn't have the "has" operator that I need.

**Comment by tiratatp** [comment]
You could write your own throttle function instead of using underscore.js. But using jQuery and Underscore makes it easier to maintain.

**Comment by tiratatp** [comment]
I wrote version 1.2.0 without external dependency.

**Comment by yan12125** [comment]
Awesome! Today responding the DMCA notice has done me :( Will test it tomorrow.
