### ISSUE TITLE
Sponsored posts still visible

### ISSUE THREAD

**Issue by AngelinCalu** [tiratatp/facebook_adblock#30]
The 'Sponsored' posts are still visible.

Maybe because the text 'Sponsored' is divided by letters, each in it's own container element. Please look at the FB source below:

`<span class="b_hlo3kw6sr d_hlo3kuzn6" data-ft="{&quot;tn&quot;:&quot;j&quot;}"><span class="fsm fwn fcg"><span class="z_hlo3kvwq7"><a class="c_hlo3kvza3 j_hlo3kvz9-" role="button" id="u_ps_0_0_d"><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 i_hlo3kvzaf">S</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 i_hlo3kvzaf">p</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 i_hlo3kvzaf">o</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 i_hlo3kvzaf">n</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 i_hlo3kvzaf">s</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 i_hlo3kvzaf">o</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 i_hlo3kvzaf">r</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 i_hlo3kvzaf">e</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 i_hlo3kvzaf">d</b></b><b class="l_hlo3kvza0 h_hlo3kvz9z y_hlo3kvz9p"><b class="l_hlo3kvza0 t_hlo3kvzac">-</b></b></b></a></span></span></span>`

**Comment by tiratatp** [comment]
Thanks, Angelin. We saw this DOM splitting behavior since February.

I think what you saw here was because other issue. I just uploaded 1.6.7, please try that and let me know if it has fixed your issue or not.

**Comment by alonmln** [comment]
Hi, I'm using 1.6.7 on Chrome 75 and it doesn't block the sponsored posts as well.
This is how I see the text:
`<div class="_5pcp _5lel _2jyu _232_" data-testid="test-id-story-sub-title" id="storymetaidNUM;NUM;0;NUM;NUM:NUM:5:0:NUM">
		<span class="g_at_lgq01s s_at_lgoy-_" data-ft="{&quot;tn&quot;:&quot;j&quot;}"><span class="fsm fwn fcg"><span class="l_at_lgpu8y"><a class="q_at_lgprj4 i_at_lgprin" id="u_ps_0_0_d" role="button"><span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq"><span class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0" data-content="S"></span>
		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0" data-content="p"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="t"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="m"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="o"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="S"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0" data-content="o"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="s"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="p"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="m"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="S"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="o"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="m"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0" data-content="n"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="a"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="n"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="h"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0" data-content="s"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="n"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="i"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="s"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0" data-content="o"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="o"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="a"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="r"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0" data-content="r"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="e"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0" data-content="e"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0" data-content="d"></span>
		</span>

		<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq">
			<span class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_" data-content="d"></span>
		</span>
		</span>
		</a></span>
		</span>
		</span>
 <span aria-hidden="true" class="_6spk" role="presentation">·</span>
 <a aria-label="Public" class="uiStreamPrivacy inlineBlock fbStreamPrivacy fbPrivacyAudienceIndicator _5pcq" data-hover="tooltip" data-tooltip-content="Public" href="#" id="js_56" role="button"><i class="lock img sp_NUM_1_5x sx_a2NUM"></i></a>
	</div>`

Anyway thanks a lot for taking the time to work on this!

**Comment by tiratatp** [comment]
The new version should catch this. Maybe there's another trick that
Facebook used.

Can you see what's the difference between the CSS of the element with
data-content S and the one before that?

**Comment by alonmln** [comment]
Hmm, that is weird, I don't see a difference, but when I look now it is different:
`<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq"><span data-content="o" class="m_at_lgprj3 d_at_lgqf0a c_at_lgpri_"></span></span>
<span class="m_at_lgprj3 t_at_lgprik a_at_lgpriq"><span data-content="S" class="m_at_lgprj3 d_at_lgqf0a v_at_lgprj0"></span></span>`

**Comment by tiratatp** [comment]
The class name is randomly generated. They are not as useful now, what we
need to know is the effective CSS on that element.

**Comment by tiratatp** [comment]
Could you try again with 1.6.9? I think I fixed another one.

**Comment by tiratatp** [comment]
I just upload 1.6.10

**Comment by tiratatp** [comment]
Close this since there's no reply from OP.

**Comment by AngelinCalu** [comment]
Sorry guys, I've become father for the second time and I really had no chance to check it out.
