### ISSUE TITLE
Ads are still appearing

### ISSUE THREAD

**Issue by juaxix** [tiratatp/facebook_adblock#34]
Hello ,I wonder how hard is to trap this one
![image](https://user-images.githubusercontent.com/996806/63373951-23cbb780-c389-11e9-9ed1-4e43bed2fa1e.png)

**Comment by tiratatp** [comment]
Thanks for reporting the bug.

Can you confirm the version of the extension you are using?

I need to see a code for a few level above this ".userContentWrapper". Can you copy the whole HTML of one the the sponsored post? Try to find the top most level parent.

**Comment by juaxix** [comment]
Yes, this is the HTML code for this particular ad
![image](https://user-images.githubusercontent.com/996806/63378600-e10edd00-c392-11e9-996f-694071cbf0cb.png)


`<div data-fte="1" data-ftr="1" class="_5jmm _5pat _3lb4 u_14tld3hn46" id="hyperfeed_story_id_5d5c4bcc7f5802d96869181" data-testid="fbfeed_story" data-cursor="MTU2NjMyOTgwMjoxNTY2MzI5ODAyOjM6MzU5MTQxMTQ5MTExMzU3NjAzMzowOjY3MjczMzUyNzU3NDQ1Mjk2NzU=" data-dedupekey="-1322896976149033958" data-timestamp="1565919937" data-referrer="hyperfeed_story_id_5d5c4bcc7f5802d96869181" aria-posinset="2" aria-setsize="10" role="article" aria-labelledby="js_a" aria-describedby="js_b" data-insertion-position="1"><div class="_4-u2 mbm _4mrt _5v3q _7cqq _4-u8" id="u_ps_0_0_b"><div class="_3ccb" data-ft="{&quot;tn&quot;:&quot;-R&quot;}" data-gt="{&quot;type&quot;:&quot;click2canvas&quot;,&quot;fbsource&quot;:703,&quot;ref&quot;:&quot;nf_generic&quot;}" id="u_ps_0_0_c"><div></div><div class="_5pcr userContentWrapper" style="" data-ft="{&quot;tn&quot;:&quot;-R&quot;}"><div class="_1dwg _1w_m _q7o"><div class="_4r_y" id="u_ps_0_0_f"><div class="_6a uiPopover _5pbi _cmw _b1e _1wbl" id="u_ps_0_0_g" data-ft="{&quot;tn&quot;:&quot;V&quot;}"><a aria-label="Opciones de la historia" data-testid="post_chevron_button" class="_4xev _p" aria-haspopup="true" aria-expanded="false" rel="toggle" href="#" role="button" id="u_ps_0_0_h"></a></div></div><div><div class="v_14tld3duta c_14tld3h0zn clearfix"><div class="clearfix i_14tld3dtpv"><a target="" class="_5pb8 q_14tld3h0zs _8o _8s lfloat _ohe" aria-hidden="true" tabindex="-1" data-ft="{&quot;tn&quot;:&quot;\u003C&quot;}" href="https://www.facebook.com/burgerkingespana/?ref=nf&amp;__tn__=%3C-R&amp;eid=ARAJGER9aTaWjPKO26Q5PymCLD29xC63PXzql0WZL-GaeevcMImOg4q2pIbXEXASPRKmabKaOsvZhiWRb770M0d0tt2blX01Mpm1PvwRsGY0gZF3Bwp4q00ttnj_axuSYCFtJJyCzi4-7KIH5misLBJPeTQkpYeq9XmAkQFW20hT3toXDg&amp;hc_ref=ARS6EoyT9yRgmgA3lwlc7DWtmPPXmBqGBqNLe61p5W1tKPiG2_is1prOa6IGSgZp2Yk&amp;__xts__%5B0%5D=68.ARAWJaDczt_M0sDy9fI343y63xpQ2LS2w8KVAVRIcMpoNI6J0RsyhRgUCecfy3lsA1mwqby_ZFC9CLewb5XBT8OcPH1csOjJYexjPdT6oZqsz4eW10DPAKpI_AygfgpExJ0TYTtd9wUVK8obPv6V7wEQc3Y5CboREqZlUkzydPqdDjQRsSG4bwEPZJ_3lUbU06SJaqksK6F3fcHUgLGBjwHk7n2Zgo01e1nmbeNi74KSNVEHxUfRrdhMadI6rGzOnHen8yhmfYdtmIhtbV36T0ZEZdyO0Adi9Qha" data-hovercard="/ajax/hovercard/page.php?id=212092952202994&amp;extragetparams=%7B%22__tn__%22%3A%22%2Cd%5Cu003C-R-R%22%2C%22eid%22%3A%22ARAJGER9aTaWjPKO26Q5PymCLD29xC63PXzql0WZL-GaeevcMImOg4q2pIbXEXASPRKmabKaOsvZhiWRb770M0d0tt2blX01Mpm1PvwRsGY0gZF3Bwp4q00ttnj_axuSYCFtJJyCzi4-7KIH5misLBJPeTQkpYeq9XmAkQFW20hT3toXDg%22%2C%22hc_ref%22%3A%22ARS6EoyT9yRgmgA3lwlc7DWtmPPXmBqGBqNLe61p5W1tKPiG2_is1prOa6IGSgZp2Yk%22%7D" data-hovercard-prefer-more-content-show="1" data-hovercard-referer="ARS6EoyT9yRgmgA3lwlc7DWtmPPXmBqGBqNLe61p5W1tKPiG2_is1prOa6IGSgZp2Yk"><div class="_38vo"><!-- react-mount-point-unstable --><div><img class="_s0 _4ooo _5xib _5sq7 _44ma _rw img" src="https://scontent.fmad3-8.fna.fbcdn.net/v/t1.0-1/p50x50/67507956_2353187211426880_3719147443011452928_n.png?_nc_cat=1&amp;_nc_oc=AQlaWSgNqo4ogBfAYQ8CISqhmVyo2WQU2keOujlIQZIswfW3pTqf6EvIMmTBRmlb8Ic&amp;_nc_ht=scontent.fmad3-8.fna&amp;oh=b7f459629ddba576de9deaa8d410c969&amp;oe=5E144CB1" alt="" aria-label="Burger King España" role="img"></div></div></a><div class="clearfix _42ef"><div class="rfloat _ohf"></div><div class="d_14tld3dtp-"><div><div class="_6a _5u5j"><div class="_6a _6b" style="height:40px"></div><div class="_6a _5u5j _6b"><h5 class="_7tae _14f3 _14f5 _5pbw _5vra" data-ft="{&quot;tn&quot;:&quot;C&quot;}" id="js_a"><span class="fwn fcg"><span class="fwb fcg" data-ft="{&quot;tn&quot;:&quot;k&quot;}"><a href="https://www.facebook.com/burgerkingespana/?__tn__=kC-R&amp;eid=ARAmvNwUz-vdWQC_ODlEJEpDxwXDM7jlo3VvJR9yTA29uN20bl4Xlap0wpGkfD5maVKeMyFMdOhDck-IWk4_96Clsc34g05ZDK0WQp4s6frHoTa4pKG82a9ShO5asvduEwPZTYV1DLZ7hyMeQ2Ak376S3chrPFxe_wbm3dDBYrMWSVCmXg&amp;hc_ref=ARRv54roWMjIDRYAvulJQlk7LKTpZN48lCnBwfJs0i2bHNBDaAMMHm3TO4BhXlvx4pI&amp;fref=nf&amp;__xts__%5B0%5D=68.ARAWJaDczt_M0sDy9fI343y63xpQ2LS2w8KVAVRIcMpoNI6J0RsyhRgUCecfy3lsA1mwqby_ZFC9CLewb5XBT8OcPH1csOjJYexjPdT6oZqsz4eW10DPAKpI_AygfgpExJ0TYTtd9wUVK8obPv6V7wEQc3Y5CboREqZlUkzydPqdDjQRsSG4bwEPZJ_3lUbU06SJaqksK6F3fcHUgLGBjwHk7n2Zgo01e1nmbeNi74KSNVEHxUfRrdhMadI6rGzOnHen8yhmfYdtmIhtbV36T0ZEZdyO0Adi9Qha" data-hovercard="/ajax/hovercard/page.php?id=212092952202994&amp;extragetparams=%7B%22__tn__%22%3A%22%2CdkC-R-R%22%2C%22eid%22%3A%22ARAmvNwUz-vdWQC_ODlEJEpDxwXDM7jlo3VvJR9yTA29uN20bl4Xlap0wpGkfD5maVKeMyFMdOhDck-IWk4_96Clsc34g05ZDK0WQp4s6frHoTa4pKG82a9ShO5asvduEwPZTYV1DLZ7hyMeQ2Ak376S3chrPFxe_wbm3dDBYrMWSVCmXg%22%2C%22hc_ref%22%3A%22ARRv54roWMjIDRYAvulJQlk7LKTpZN48lCnBwfJs0i2bHNBDaAMMHm3TO4BhXlvx4pI%22%2C%22fref%22%3A%22nf%22%7D" data-hovercard-prefer-more-content-show="1" data-hovercard-referer="ARRv54roWMjIDRYAvulJQlk7LKTpZN48lCnBwfJs0i2bHNBDaAMMHm3TO4BhXlvx4pI">Burger King España</a></span></span></h5><div class="_5pcp _5lel _2jyu _232_" id="fbfeed__sub_header_id_263;212092952202994;0;2318854071526861;1561719586:-1322896976149033958:5:0:43468" data-testid="fb-test-id_feedsubtitle"><span class="m_14tld3c9-1 t_14tld3dllw" data-ft="{&quot;tn&quot;:&quot;j&quot;}"><span class="fsm fwn fcg"><span class="s_14tld3cqa9"><a class="w_14tld3cnch x_14tld3cnc-" href="#" role="button" id="u_ps_0_0_d"><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="l" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="h" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="t" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="S" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="p" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="P" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="r" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="t" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="l" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="u" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="s" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="b" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="o" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="n" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="l" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="i" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="s" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="o" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="i" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="c" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="r" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="l" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="i" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="s" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="o" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="e" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="d" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="d" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="a" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="m" class="e_14tld3cnci m_14tld3fpqh u_14tld3cncm"></span></span><span class="e_14tld3cnci b_14tld3cnd1 k_14tld3cncx"><span data-content="d" class="e_14tld3cnci m_14tld3fpqh y_14tld3cncl"></span></span></span></a></span></span></span><span class="_6spk" role="presentation" aria-hidden="true"> · </span><a class="uiStreamPrivacy inlineBlock fbStreamPrivacy fbPrivacyAudienceIndicator _5pcq" aria-label="Personalizado" href="#" role="button" data-hover="tooltip" data-tooltip-content="Personalizado"><i class="lock img sp_o2lM5Mps4LI sx_8f821c"></i></a></div></div></div></div></div></div></div></div><div data-testid="post_message" class="_5pbx userContent _3576" data-ft="{&quot;tn&quot;:&quot;K&quot;}" id="js_b"><p>Es hora de volvernos a ver. Entra en Burger King en casa y realiza tu pedido.</p></div><div class="_3x-2" data-ft="{&quot;tn&quot;:&quot;H&quot;}"><div data-ft="{&quot;tn&quot;:&quot;H&quot;}"><div class="mtm"><div id="u_ps_0_0_e" class="_6m2 _1zpr clearfix _dcs _4_w4 _41u- _59ap _2bf7 _64lx _3eqz _20pq _3eqw _2rk1 _3n1j _5qqr" data-ft="{&quot;tn&quot;:&quot;H&quot;}"><div class="clearfix _2r3x"><div class="lfloat _ohe"><span class="_3m6-"><div class="_6ks"><a href="https://l.facebook.com/l.php?u=AT2OfDiUI-QuB9pUHUDn2EICVK1qY-4tRj3zqwEIbb-KvASZR6PjqTzXgYYR3TPCc3ewOtFTFuxXgtp0ae9dCRLA2plcL9juGQlnZxIY2gJq7Bg35LKWa3_yrWLsUF1GoI7iGol4YXarDCQYJ2oLFBk85UUX9dKcpR5e7nWoY4SxDhmPIcaW7_xFFNkv9Nyf_8CuHQzk_HoIJ6ZPzHr-04GUsJ-DdaNXLuh2gElchUOtvbJJlzRP4dtqRvuaOxuwyxMygWLepXNrN20lBQMtjW7lyMkfDpn39udkygA&amp;h=AT1FOmSnitIJzhFkBHdb58Em_-pkaFu3Jvzc4aaiapgrmSvbSIrOz2hurAG01b3bhIeGFEMsrfbEW0OsPIReJndhxZ1XvqQXftSkWWknnq6AqexS8aOrFYdOJvzgPlB8a1wFdkARx2Ay-Z1eZ8m3N01ya5PMLDGCUzyAwJ8lIg5sOQzmM8s1AlHh3khvP_mGzMdFwhlafvwyY-PPJYfRX-k6FjmlAIqp7mWKq-Y6AbSB3-ODtBzFZLw7VPkcfts-FGfrGvJHkrA27DXN5SmgbOU1eeT-QlhmkGGs1rjA4GVwtppebwK3iTHmrIQ9Yq7Ls8KN2IAWbf_LPLKWqDi4ckuMtBQdtUbODLKkezWZ7-6sILTWWr0lYYQcePbvNDrIJl1L8k5oK75hRri6ecWKzVUEQwlhxpYdy40zb9fCKdhNWcZd841XAikekzQN4XlnC62le5cQS96fu2bnECNeBllG1r2B9fhjdg1uDLXFDc8dTrxTuH6VJ8W0m14b2Emfyrt9HMNp3xCCRwAeiKbop9MFTmXwLPOVQvnW1KE5-KytJZXZUA" tabindex="-1" target="_blank" rel="noopener nofollow"><div class="_6l- __c_"><div class="uiScaledImageContainer _6m5 fbStoryAttachmentImage" style="width:500px;height:261.40684410646px;"><img class="scaledImageFitWidth img" src="https://scontent.fmad3-5.fna.fbcdn.net/v/t45.1600-4/cp0/q90/spS444/c0.0.1200.629a/s526x296/43949041_6126633869739_1407437817709068288_n.png.jpg?_nc_cat=106&amp;_nc_oc=AQnAaXH0GKw2s86ftUdGu1z5yCgTqOFoY1LkA06Rits1KhmO9E8OffNdQ3dausILh78&amp;_nc_ht=scontent.fmad3-5.fna&amp;oh=2fa5cdffa9421514335927643dd98bdf&amp;oe=5DCF4F17" data-src="https://scontent.fmad3-5.fna.fbcdn.net/v/t45.1600-4/cp0/q90/spS444/c0.0.1200.629a/s526x296/43949041_6126633869739_1407437817709068288_n.png.jpg?_nc_cat=106&amp;_nc_oc=AQnAaXH0GKw2s86ftUdGu1z5yCgTqOFoY1LkA06Rits1KhmO9E8OffNdQ3dausILh78&amp;_nc_ht=scontent.fmad3-5.fna&amp;oh=2fa5cdffa9421514335927643dd98bdf&amp;oe=5DCF4F17" style="top:0px;" alt="" width="500" height="262"></div></div></a></div><div class="_3ekx _29_4"><div class="m_14tld3cluz"><div></div><div class="_6m3 _--6 j_14tld3cljs"><div class="_59tj _2iau"><div><div class="_6lz _6mb _1t62 ellipsis">www.burgerkingencasa.es</div><div class=""></div></div></div><div class="_3n1k"><div class="mbs _6m6 _2cnj _5s6c"><a href="https://l.facebook.com/l.php?u=AT0piRB5HdEI9l1GCN7yUny9grH3LLGbEE-oEp9ZZlLBLuG1qQ1HM_DvfgKeZqDRrScCcYWaD57h26hEGv0EvEwzEngtX6HfKvc-zUOUaQ4sjmlwORtfO6Ns4jfLfkEoZKpchEdXBiFLmY69SCpv_Sdk2Koc5RKW5Xa3M8telvuHbQ9f8nFHUX02w68bZkUHr_Yn8AepOdTV1Quz_9E42KKYlCmrbkBaZeE492qxgrYTWWcvtS0zUFidSLBqPwcsHBUk47-d5Boodz3AEC_NFbBRothGD4rQNLUzKDc&amp;h=AT3ngSJXbNLPgAqQzLq2CcpNUm8rg9Zb9w6WO9NN0QNhbzi9OQ4CbY6oKqhmM8GAmMrmllLyScWJPd0a2ztPt9VezAOWWLGnlVpW5vom5QU1pt5SctQpm3yBIayquf58cwjPT2Ai84fViTNx5893KcQmI6qxU_I1kO0QTZRFlfFbd_dae7ChljCRcMixWdzuqCClgkQq7QYd77O2ooNLzdYqtBkrvlYj-qJQb8rviFHb6EjaoTeAWFWNzIigZr0_iNUsN5HuavA-0qApa_jXcDvUgb6Y4Bh9phgHVpBIS_Swa8fOH7nnvRwtDpiy0DtGIGq33MnNxJ2yn5fNte3ozI8huOsIIP_AiOFFV6MGGTutVXJl5h2R91o91d3BQIvi7w54GEmrgCuLZOSoxF6UaIF3x4iNY0PVeKyAC739IocLQ-6BB4IT__yCLi5Zc4mBLwiNrI1YNXfZpv4dALlXAPNg5g99_45DHVzk19SPY9R6QURsuXV5o1deR6d0W2qC4kOPw_K0c9D9j5IXreoiq-HQiUuV2SPTC_uXCok3H8ANwLBvyw" rel="noopener nofollow" target="_blank"></a></div></div></div><div class="g_14tld3civ2"><div class="h_14tld3clid"><div class="_6a" data-ft="{&quot;tn&quot;:&quot;*J&quot;}"><a class="c_14tld3cpe_ q_14tld3cpf4 x_14tld3cpe- b_14tld3cpf1" href="https://l.facebook.com/l.php?u=AT3qRTfueZGZ-sVd6uEF5_tnf50ruaH8amBTBAtc5iHTeFkHz2B_8tdTV2S3vkxy5hB-lSUV9GrBDbY-S-vJH7mrVmHdVYqk_cIIb_zdClj9HE_LRM91D1IR48wvYvMuA8uexzZaFTPdZiD5hXo87_c78hrlfHzHghoDJBO0pHwFWupJLBqcXnYsIhFBXcCVt93qiZlxKm7gqLO4eyE7Mmr1Eoa6JEJ8t9am2-PJY5Du5pGXWXEhDUQLpePaUWy6lcFzUD2wK6UbvR0C1MVHiw_DjQ7tEwEjEWIFfoc&amp;h=AT1lncwg9hGARcLdAgP943VMnxNL_KlzBERfqeJWZ6AcSafrk0VwtJ00ib7OWC_DelYasp5knMblK6gKLiH4sfijHzyMvAprZcEW5888aDq8Nt4QYiSwbUQHJTJtIQNtunuC2oTTr2Pclg7XaFx8OniKhryQR4GGugDux1KqIYVuOVgEWMHuL7Dc1YelT2P2uYvZ6izZ12spthGubhsgzIjuoX2u2d991BPJk49yAqCDEQTnyFstPOd0Ltu44x-Gq6b9LaX6jWbHJD-QFoOnRh4YOekl2GoDpJmnbgMLtyNMoqj_nj05KEuO8rmG8Qhy_vBCB1R5u1gYJZUtFHayR25G99Sx3I1Z3t5hPvTZAUhE9uDu_T0Rq2_upoycQ9XO-BtK-Ic3jNcyP2o6n8ujo6pV3IvY7pOqy18iiNZolN5t1v3rk-cI7iSKg3ya562GJ4pEexABam-XK_3JrbdjsjthGq58Rv949hVTZHKd4K2V0eQgDq56a4BSFL-eR7b-AXGVfcQKZg6L70YqMhNABA8aCxzRxhGF9whD279dM342Hhe4UrJtASM" target="_blank" rel="noopener nofollow">Más información</a></div></div></div></div><a href="https://l.facebook.com/l.php?u=AT3GeJKS_HMn6U5k8i0PNpxh8Msz3yI52Ig08isy_Ezyad0D3rc4ygvdt1mvuWCS600YU4LbD-2zGurvNFqruoSszGtDMMDzKjWekSDTv7g_o9EWu5lwSova3MNT5gHytpyVr98AyBgOcQ_e3SoIrYNwJBKiDGxJkScxLjUCx2cV5KYu7pSd-YDSF0Lp7xhLSP6pTezDoDG8trE3J6XzgfZrb5aAscCL3TdrT9WZR6Gdurjqrjli9OkMwlQreCySEMQWBzdzNp985YFLSKh3mOxo1BHk_EuJgspHKwQ&amp;h=AT2TOETweG2fOkHKWqL46OMsNeZYeKFvEv5pszUVgWc_QHnrZXzs8Xy3tWrAApAIQgvC2EGJkFCDTH3_RRa8WB0LMfcsnQloVMaSyHUOoagVWpcB2oS32zd-YH0d8bjzCE5vMJVA-ud8T-5bGX8qkQlsPua8-pZVU_Jg6UwA40FEsy7nXlz9iwd_F2VLIET-IarU2t2838ti8A3YnHTrUflJMeLzoIITFdZZOxxA5Wwhk22bWGv9_dfQIezvcZVOXQ2w0ufMYsnvkeg4Y-hJvUHJkvOv4kBKxOJROqrxkYVVwNLMKM9RvnEVZbUXlVDFYzdPKildj8QwWTlemZmntn4396E_FQcmHaP8jL2KRS9o3W85mZy60SYqPFyb9X4L7QhRGmsnbK5qEDenWYh4eaA5Q3nb9ikEYVeqwXHrGXmClf0xF45iCp0TNkt07cNgXwkbjQJVOWYsJFn2MULQEX-p05SCokkl9FMc05HVhAwD7yiFc8DC7ZDmwzjLAcsMWlaAn8SuvLw3rCOy7p5CEyZ417N_hVkEj7TtJ1wPNQjO4dpB9NK8jrTuNLY" rel="noopener nofollow" tabindex="-1" target="_blank" class="_52c6"></a></div></span></div><div class="_42ef"><span class="_3c21"></span></div></div></div></div></div></div><div></div></div></div><div><form rel="async" class="commentable_item collapsed_comments" method="post" data-ft="{&quot;tn&quot;:&quot;]&quot;}" action="/ajax/ufi/modify.php" onsubmit="" id="u_ps_0_0_j"><input type="hidden" name="jazoest" value="21979" autocomplete="off"><input type="hidden" name="fb_dtsg" value="AQGlHs4BOGzk:AQFth-7_PH9H" autocomplete="off"><input type="hidden" autocomplete="off" name="ft_ent_identifier" value="2318854071526861"><input type="hidden" autocomplete="off" name="data_only_response" value="1"><div class="_4299"><div class="_5vsi"></div><div><div class="_78bu"><div class="_68wo" data-testid="fbFeedStoryUFI/feedbackSummary"><div class="_3vum"><div class="_66lg"><span aria-label="Consulta quién reaccionó a esto" class="_1n9r _66lh" role="toolbar"><span class="_1n9k" data-testid="UFI2TopReactions/tooltip_LIKE" tabindex="-1" data-hover="tooltip"><a ajaxify="/ufi/reaction/profile/dialog/?ft_ent_identifier=ZmVlZGJhY2s6MjMxODg1NDA3MTUyNjg2MQ%3D%3D&amp;reaction_type=1&amp;av=589114159" href="/ufi/reaction/profile/browser/?ft_ent_identifier=ZmVlZGJhY2s6MjMxODg1NDA3MTUyNjg2MQ%3D%3D&amp;av=589114159" rel="dialog" aria-label="69 Me gusta" class="_1n9l" tabindex="0" role="button"><span class="_9zc _19kl _1n9q"><i class="_3j7l _2p78 _19kl"></i></span></a></span><span class="_1n9k" data-testid="UFI2TopReactions/tooltip_ANGER" tabindex="-1" data-hover="tooltip"><a ajaxify="/ufi/reaction/profile/dialog/?ft_ent_identifier=ZmVlZGJhY2s6MjMxODg1NDA3MTUyNjg2MQ%3D%3D&amp;reaction_type=8&amp;av=589114159" href="/ufi/reaction/profile/browser/?ft_ent_identifier=ZmVlZGJhY2s6MjMxODg1NDA3MTUyNjg2MQ%3D%3D&amp;av=589114159" rel="dialog" aria-label="5 Me enoja" class="_1n9l" tabindex="-1" role="button"><span class="_9zc _19kl _1n9q"><i class="_3j7q _2p78 _19kl"></i></span></a></span><span class="_1n9k" data-testid="UFI2TopReactions/tooltip_HAHA" tabindex="-1" data-hover="tooltip"><a ajaxify="/ufi/reaction/profile/dialog/?ft_ent_identifier=ZmVlZGJhY2s6MjMxODg1NDA3MTUyNjg2MQ%3D%3D&amp;reaction_type=4&amp;av=589114159" href="/ufi/reaction/profile/browser/?ft_ent_identifier=ZmVlZGJhY2s6MjMxODg1NDA3MTUyNjg2MQ%3D%3D&amp;av=589114159" rel="dialog" aria-label="3 Me divierte" class="_1n9l" tabindex="-1" role="button"><span class="_9zc _19kl _1n9q"><i class="_3j7o _2p78 _19kl"></i></span></a></span></span><a ajaxify="/ufi/reaction/profile/dialog/?ft_ent_identifier=ZmVlZGJhY2s6MjMxODg1NDA3MTUyNjg2MQ%3D%3D&amp;av=589114159" href="/ufi/reaction/profile/browser/?ft_ent_identifier=ZmVlZGJhY2s6MjMxODg1NDA3MTUyNjg2MQ%3D%3D&amp;av=589114159" rel="dialog" class="_3dlf" data-testid="UFI2ReactionsCount/root" tabindex="0" role="button"><span aria-hidden="true" class="_3dlg"><span class="_3dlh" data-hover="tooltip"><span class="_81hb">78</span></span></span><span class="_3dlh _3dli" data-testid="UFI2ReactionsCount/sentenceWithSocialContext"><span data-hover="tooltip"><span class="_81hb">78</span></span></span></a></div><div class="_1r48"></div><div class="_4vn1"><span class="_1whp _4vn2" data-hover="tooltip"><a class="_3hg- _42ft" data-ft="{&quot;tn&quot;:&quot;O&quot;}" data-testid="UFI2CommentsCount/root" role="button" href="https://www.facebook.com/burgerkingespana/posts/2318854071526861?comment_tracking=%7B%22tn%22%3A%22O%22%7D">34 comentarios</a></span><span class="_355t _4vn2" data-hover="tooltip"><a ajaxify="/ajax/shares/view?target_fbid=2318854071526861&amp;av=589114159" class="_3rwx _42ft" data-testid="UFI2SharesCount/root" href="/shares/view/?av=589114159" rel="dialog">1 vez compartido</a></span></div></div></div><div class="_1dnh"><div class="_1dnk _29ak"><span><a type="button" class="_55pi _2agf _4o_4 _4jy0 _4jy3 _517h _51sy _59pe _42ft" aria-haspopup="true" role="button" href="#" style="max-width: 200px;"><span alt="" class="_-xe _3-8_"><span><img class="_6vg img" height="16" src="https://scontent.fmad3-8.fna.fbcdn.net/v/t1.0-1/p32x32/29136279_10155737208664160_2441949723960016896_n.jpg?_nc_cat=108&amp;_nc_oc=AQnbgGLcU62iJxeGrqvPvs18ZjE3wdDcH9YDTzQRohY-ou6ZYPk9PPVQQVZHHWtwiFU&amp;_nc_ht=scontent.fmad3-8.fna&amp;oh=4d30520526d578bf61a77827afe82ccf&amp;oe=5DD086C3" width="16" alt=""></span></span><span class="accessible_elem"><span class="_55pe">Juan Xix</span></span><span alt="" class="_4o_3"><i alt="" class="img sp_DzAtg7ltJ8m sx_d8d94f"></i></span></a></span></div><div class="_3vuz"><span class="_18vi"><div class="_666k" data-testid="UFI2ReactionLink/actionLink"><div class="_8c74"><a aria-pressed="false" class=" _6a-y _3l2t  _18vj" data-testid="UFI2ReactionLink" href="#" role="button" tabindex="0"><i class="_6rk2 img sp_DOVwx90K0FX sx_21efd4" alt=""></i>Me gusta</a><button class="accessible_elem" tabindex="-1" type="button">Mostrar más reacciones</button></div></div></span><span class="_18vi"><a class=" _666h  _18vj _18vk _42ft" role="button" tabindex="0" testid="UFI2CommentLink" title="Dejar un comentario" href="#">Comentar</a></span><span class="_18vi"><span class="_1j6m"><a class=" _2nj7  _18vj _18vk" data-ft="{ &quot;tn&quot;: &quot;J&quot;, &quot;type&quot;: 25 }" href="#" role="button" tabindex="0" title="Enviar esto a tus amigos o publicarlo en tu biografía">Compartir</a></span></span></div></div></div></div><!-- react-mount-point-unstable --></div></form></div></div></div></div><div></div></div>`

and the version I'm using is: 1.6.10

**Comment by tiratatp** [comment]
I'll upload the new version when I get home.

**Comment by tiratatp** [comment]
Version 1.6.11 published

**Comment by juaxix** [comment]
Worked perfectly :) good catch btw!
