### ISSUE TITLE
Suggested Posts are back

### ISSUE THREAD

**Issue by dhicks** [tiratatp/facebook_adblock#4]
This extension has worked well for me since last year.  However, over the last few weeks, I've noticed Suggested Posts have started showing up in my feed again.  I'm attaching a txt containing the html of a Suggested Post that's on my feed right now.  

[suggested post.txt](https://github.com/tiratatp/facebook_adblock/files/753030/suggested.post.txt)

**Comment by tiratatp** [comment]
Fixed in 1.1.5
