### ISSUE TITLE
It stopped working.

### ISSUE THREAD

**Issue by gellenburg** [tiratatp/facebook_adblock#41]
Brave Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)

Sponsored posts have returned.

**Comment by tiratatp** [comment]
Can you share a screen shot?

**Comment by gellenburg** [comment]
Ok, that's weird. Now it's working. I swear it wasn't working earlier today.

Sorry for the trouble.

**Comment by tiratatp** [comment]
No worry. It takes a few seconds for the extension to hide the posts.

**Comment by dodona2** [comment]
--- Ursprüngliche Nachricht ---
Von: George Ellenburg <notifications@github.com>
Datum: 05.10.2019 22:48:52

> Brave Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
>
> Sponsored posts have returned.
>
> --
same with Waterfox 56.2.14
