### ISSUE TITLE
When will this be ready for Chrome?

### ISSUE THREAD

**Issue by pa28236** [tiratatp/facebook_adblock#47]
I see there have been changes to create version 1.73 for Mozilla. When will this be ready for Chrome? There are a lot of "Sponsored" ads that are not getting blocked in Chrome.
Thanks!

**Comment by tiratatp** [comment]
Thanks for contacting me. The extension is still being reviewed by Google.
They said it will take a few business days.

**Comment by tiratatp** [comment]
It has been a week, but they said it could take weeks. They also said I could open a ticket if it takes longer than 3 weeks. https://developer.chrome.com/webstore/faq#faq-listing-108

**Comment by pa28236** [comment]
Thanks for the reply. Appreciate the good work you are doing. I’ll sit tight!

**Comment by tiratatp** [comment]
I cut them another ticket today.

**Comment by tiratatp** [comment]
1.7.3 is now live in Chrome Web Store after a help from Chrome Web Store team.

I also published 1.7.4 but it will need to go through another review.

**Comment by pa28236** [comment]
Works perfectly now. Thank you!!!

**Comment by tiratatp** [comment]
1.7.4 is also on Chrome
