### ISSUE TITLE
New changes from FB?

### ISSUE THREAD

**Issue by dan2bit** [tiratatp/facebook_adblock#48]
As spotted in the wild today (Chrome extension 1.72) Chrome Version 80.0.3987.149 - the code snippet below is the "Sponsored" span for a post that got through, as shown in Chrome Inspector. 

`<span class="f_1am1fq514z"><a class="k_1am1fq541x x_1am1fq541-" role="button" id="u_fetchstream_5_16" aria-labelledby="4e43b979-8995-4e15-86f7-3ac97ea12a74"><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="S" class="g_1am1fq541u y_1am1fq0wg3 y_1am1fq541l"></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="c" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="e" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="t" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="S" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="p" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="f" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="p" class="g_1am1fq541u y_1am1fq0wg3 y_1am1fq541l"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="o" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="t" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="n" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="s" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="o" class="g_1am1fq541u y_1am1fq0wg3 y_1am1fq541l"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="S" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="m" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="n" class="g_1am1fq541u y_1am1fq0wg3 y_1am1fq541l"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="o" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="r" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="a" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="e" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="s" class="g_1am1fq541u y_1am1fq0wg3 y_1am1fq541l"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="d" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="m" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="i" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="o" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="o" class="g_1am1fq541u y_1am1fq0wg3 y_1am1fq541l"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="d" class="g_1am1fq541u y_1am1fq0wg3 e_1am1fq541i"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="r" class="g_1am1fq541u y_1am1fq0wg3 y_1am1fq541l"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="e" class="g_1am1fq541u y_1am1fq0wg3 y_1am1fq541l"></span></span><span class="g_1am1fq541u z_1am1fq541z i_1am1fq542b"><span data-content="d" class="g_1am1fq541u y_1am1fq0wg3 y_1am1fq541l"></span></span></span></a></span>`

**Comment by dodona2** [comment]
I confirm that. I'm forced using 0.2.1, hope the bug fix will be applied to this outdated plugin.

**Comment by tiratatp** [comment]
Hey thanks for reporting the bug. I'll look through them and get back to
you.

**Comment by tiratatp** [comment]
Fixes in 1.7.4 @yan12125  can you help upload to Firefox?

**Comment by tiratatp** [comment]
Chrome extension update are blocked by #47

**Comment by yan12125** [comment]
Thanks for the update! 1.7.4 is uploaded https://addons.mozilla.org/zh-TW/firefox/addon/fb_ad_block/versions/.
