### ISSUE TITLE
Looped loading of items

### ISSUE THREAD

**Issue by risototh** [tiratatp/facebook_adblock#50]
Today, the extension loops loading and deleting the facebook posts.
See it on my video https://youtu.be/d1wTpoNyY1E

**Comment by raymondsteers** [comment]
Same issue on Chrome Version 80.0.3987.149 (Official Build) (64-bit) (macos)

**Comment by cbotsikas** [comment]
wow. unbelievable... I can confirm. They've updated facebook and the date is no longer in an abbr element but scrambled with span line the "Sponsored" text. I'll PR a fix. I guess they are monitoring plugin development like this one, if you consider that we pushed the new rule yesterday and was patched already... 
![image](https://user-images.githubusercontent.com/1640100/78681531-27e32000-78ed-11ea-9414-a3ce6a2d594c.png)

**Comment by tiratatp** [comment]
Fixed in 1.7.6. Sorry about this guys.
