### ISSUE TITLE
Facebook Adblock does/will not work with new facebook UI

### ISSUE THREAD

**Issue by arslnb** [tiratatp/facebook_adblock#53]
I'm on the beta for the new facebook all-ReactJS UI featuring dark mode etc, and the plugin breaks. Just a heads up :) 

Check out the screensot. Plugin version 1.7.6, Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)

Can still see all ads in the timeline as well as the sidebar. 

<img width="1904" alt="Screen Shot 2020-04-07 at 4 17 08 PM" src="https://user-images.githubusercontent.com/2177963/78728245-b35bb180-78eb-11ea-9e37-a5be503af637.png">

**Comment by cbotsikas** [comment]
@arslnb I've created PR #54 to support the new FB5 design. In my tests though, I never got a sponsored ad on the right sidebar so i've only addressed the sponsored feed posts.

**Comment by tiratatp** [comment]
@arslnb can you take a look at #54 and maybe comment?

**Comment by tiratatp** [comment]
Fixed in 1.8.0

**Comment by tiratatp** [comment]
Hey @yan12125 could you help us publish this new version? Thank you!

**Comment by yan12125** [comment]
Updated :)
