### ISSUE TITLE
Refactor a code into FB5 code path and older FB code path

### ISSUE THREAD

**Issue by tiratatp** [tiratatp/facebook_adblock#57]
## Why?

Right now `onPageChange()` is shared between old Facebook and FB5 code path. We should refactor old code and new old into two distinct functions so we could deprecate old code easily.

## Acceptance Criteria
- Two new functions that do not share variable or state
   - One should handle old Facebook; another should handle FB5
- If possible, we should refactor old code into a new file so we can easily remove

**Comment by tiratatp** [comment]
Do you have bandwidth to work on this @cbotsikas

**Comment by cbotsikas** [comment]
I could have a look on Friday

**Comment by tiratatp** [comment]
Also fixed by 23e2fd1fd149552dfac38e84e6e29f11a47fba82
