### ISSUE TITLE
Explore the possibility of using Firefox addon action

### ISSUE THREAD

**Issue by tiratatp** [tiratatp/facebook_adblock#58]
Can we use this to auto publish to Firefox https://github.com/marketplace/actions/firefox-addon-action

**Comment by tiratatp** [comment]
@yan12125 do you think it's possible to create a new secret key for this addon?

**Comment by cbotsikas** [comment]
May I ask why isn't the firefox add-on published by you? 
Just in case you didn't know, Mozilla allows to have multiple owners and authors or even transfer ownership. You can find more info [here](https://extensionworkshop.com/documentation/publish/add-on-ownership/)

**Comment by tiratatp** [comment]
I wasn't using Firefox at the time, and Chih-Hsuan said he could do it.

**Comment by tiratatp** [comment]
I tried using Chrome Action to publish and I think it's working. The secrets are stored in github can never read back.

**Comment by yan12125** [comment]
Thank you very much for the invitation and this great proposal! I am +1 for automatic publishing. I will try it out for the next version.

> do you think it's possible to create a new secret key for this addon?

I guess not. As far as I know Mozilla addon publishing key is per-account.

---

TODOs
* Check if https://github.com/trmcnvn/firefox-addon is secure or not
* Read https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses and use git commit SHA1 instead of a tag

**Comment by tiratatp** [comment]
It stores secrets with a Github repo. I did that for my Google API Key for Chrome publishing.

You can put any secrets and you cannot read it back. Not even me can read.

**Comment by tiratatp** [comment]
See https://github.com/tiratatp/facebook_adblock/settings/secrets

**Comment by yan12125** [comment]
> See https://github.com/tiratatp/facebook_adblock/settings/secrets

Hmm I cannot access that page.

> For a user account repository, you must be the repository owner to create encrypted secrets.

(https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)

**Comment by tiratatp** [comment]
Hey @yan12125 I got this to auto publish to Chrome. Do you think it's possible to add me as a co-owner of your Firefox extension, so I could extract the secret keys for the auto publish purpose. Then you can remove me.

**Comment by yan12125** [comment]
Sure! Looks like adding a co-owner requires the email address. Do you use the same email for the Mozilla account as the one you've sent mails to me?

**Comment by tiratatp** [comment]
You can use that email.
—
Tiratat Patana-anake

**Comment by yan12125** [comment]
Hmm, Mozilla tells me "No user with that email."

**Comment by tiratatp** [comment]
Oh I need to sign up first.

**Comment by tiratatp** [comment]
I sent you an email with my other email for this.

**Comment by tiratatp** [comment]
I set it up, but I haven't tested yet since we just release 1.8.1.

**Comment by tiratatp** [comment]
It works! Now we can tag and it will publish to both Firefox and Chrome! Thank you for your help, @yan12125 and @cbotsikas

**Comment by yan12125** [comment]
Great!
