### ISSUE TITLE
New sponsored DOM

### ISSUE THREAD

**Issue by cbotsikas** [tiratatp/facebook_adblock#59]
Today some sponsored posts appeared. They've changed the DOM again..
![Annotation 2020-04-23 133325](https://user-images.githubusercontent.com/1640100/80095675-99b39e80-8568-11ea-9a54-4ef9d33e9643.jpg)

After further debugging, the injected post's DOM is using a div[role=button] (Image 1) to wrap the sponsored label and then it's changed to a[role=link] (Image 2).

Image 1:
![Annotation 2020-04-23 135847](https://user-images.githubusercontent.com/1640100/80096874-9b7e6180-856a-11ea-8afd-9d1cbf3324cc.jpg)

Image 2:
![Annotation 2020-04-23 135851](https://user-images.githubusercontent.com/1640100/80096886-a0dbac00-856a-11ea-96b6-7553881bd2fa.jpg)

**Comment by tiratatp** [comment]
Merged

**Comment by cbotsikas** [comment]
@tiratatp will you release that?

**Comment by tiratatp** [comment]
Sorry for the delay. I wanted to test the publish workflow. It worked now! Next time if you want to publish this to Chrome, remember to bump version in two places: `package.json` and `static/manifest.json`

**Comment by tiratatp** [comment]
The new version is pending Google review. It shouldn't take too long.

**Comment by cbotsikas** [comment]
> Sorry for the delay. I wanted to test the publish workflow. It worked now! Next time if you want to publish this to Chrome, remember to bump version in two places: `package.json` and `static/manifest.json`

I was worried when I saw the workflow executing for my PR..
May I suggest to use Tags instead in order to trigger the auto publish? This way you should have more control and be able to merge multiple commits/PRs before triggering the publish mechanism. It should also prevent from accidental publishing without changing the version number. 
I found the following searching:
```
on:
  push:
    tags:
    - '*'
```

**Comment by tiratatp** [comment]
Yeah I was worried too haha. But luckily it failed.

I'll make the change over the weekend.

Stay safe!
—
Tiratat Patana-anake
