### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by romgrk** [tiratatp/facebook_adblock#64]
The extension works when I configure FB to be in en-US, but in my other locale (fr-CA) ads show up.

**Comment by cbotsikas** [comment]
Hi @romgrk, what's the translation for "Sponsored" in french? Currently the plugin supports the languages [specified here](https://github.com/tiratatp/facebook_adblock/blob/master/src/constants.js#L14-L37)

**Comment by cbotsikas** [comment]
and just realised that it has "Sponsorisé" for French... 
Do you see something different when using fr-CA? Can you share a screenshot of an ad?

**Comment by Leibeun** [comment]
In canadian french it's Commandité

**Comment by romgrk** [comment]
I concur with @Leibeun, FB shows "Commandité" in fr-CA locale.

**Comment by tiratatp** [comment]
@cbotsikas do you want to bump a version, tag and send another pull request?

**Comment by cbotsikas** [comment]
Yes, I'll try that in the morning. I didn't do it cause I wasn't sure if it would trigger before merging..

**Comment by cbotsikas** [comment]
@romgrk @Leibeun fr-CA is now supported by v1.8.3 and is already live on both Chrome and Firefox stores. Your browser should automatically update the plugin.
