### ISSUE TITLE
Supported Groups on Mobile

### ISSUE THREAD

**Issue by tiratatp** [tiratatp/facebook_adblock#7]
@yan12125 do you know what's the "Supported Groups" that the user was talking about on Firefox?

> Just downloaded it for Foxfire 50, Android 6.0.1. Went to Facebook.com...the annoying Supported Groups still show. Is it not supported for my platforms?

I tried using Chrome to emulate mobile devices but I could not find this.

**Comment by yan12125** [comment]
Dunno. Maybe ask him/her for a screenshot?

**Comment by tiratatp** [comment]
Could you reply with the instruction to get a screenshot?

**Comment by yan12125** [comment]
AFAIK steps to take a screenshot vary among different Android phones.

**Comment by yan12125** [comment]
Ahh, I didn't realize you were talking about comments on https://addons.mozilla.org/en-US/firefox/addon/fb_ad_block/... I've edited my original reply

**Comment by tiratatp** [comment]
Probably not relevant anymore.
