### ISSUE TITLE
Extension appears inactive on Chrome in Silicon M1 mac

### ISSUE THREAD

**Issue by lynXand** [tiratatp/facebook_adblock#76]
Not able to get the extension to activate on facebook.com. Extension settings are default including allowing activation on facebook.com.

**Comment by tiratatp** [comment]
A platform of your mac should not affect this extension (or any extension). 

What's the error message? What's the version of your Chrome? Any screenshot showing the problem?

**Comment by Goa8** [comment]
I see. I only noticed it today after having changed to the M1 macbook a few days ago, so figured it may have something to do with the mac.

Chrome version -- Version 87.0.4280.88 (Official Build) (arm64)

No error message. Just inactive. Here are the screenshots showing this: https://imgur.com/a/LML41nM As you can see, behind the first screenshot are facebook's "sponsored" ads.

**Comment by Goa8** [comment]
PS. I'm not sure if it's actually abnormal for the extension to be not clickable (greyed out) as in the picture above, but I started seeing this today in the right sidebar: https://imgur.com/Yua3KWA

**Comment by krystian3w** [comment]
> A platform of your mac should not affect this extension (or any extension).

Only if run correct on Android in Kiwi/Yandex(in the feature too ungoogled chromium).

**Comment by tiratatp** [comment]
I don't understand your post, @krystian3w.

@lynXand is this problem still exists? I don't know if there is anything an extension developer can do. Did you try to uninstall and reinstall?

**Comment by krystian3w** [comment]
If addon works bad on ARM Android processors (Snapdragon/Mediatek/Kirin/Exynos) so can works bad on ARM Apple processor.

**Comment by tiratatp** [comment]
> If addon works bad on ARM Android processors (Snapdragon/Mediatek/Kirin/Exynos) so can works bad on ARM Apple processor.

Like I said before, this extension does not do anything fancy. It's just css and js, and no native code. So that's why I said I don't know why it would not work.

Do you know how to fix this? Or maybe a link to some documentation about this?

**Comment by tiratatp** [comment]
I'll close this since I don't think it's what an extension developer can fix.
