### ISSUE TITLE
Stopped working on chrome (Win. 10)

### ISSUE THREAD

**Issue by Yolakalemowa** [tiratatp/facebook_adblock#77]

**Comment by pa28236** [comment]
Yes, broken now. I'm getting all kinds of Sponsored ads in my feed. 
Also, it would be great if the "Suggested for you" posts could be removed as well. Either by having a toggle in the settings to allow or remove , would be great!

**Comment by tiratatp** [comment]
An issue like this is not useful for us developer since it provides nothing to help us solve this issue.

I recently published 1.9.0 to fix an issue with ads showing after changing a page in FB5. Please try and create a new issue along with anything you could provide to help us debug this.
