### ISSUE TITLE
Some normal posts are blocked too.

### ISSUE THREAD

**Issue by Ricci36** [tiratatp/facebook_adblock#78]
I just found out that a lot of normal posts are invisible now when the adblocker is active. When I search for them I can find and display them.

When I go into this profile:
https://www.facebook.com/profile.php?id=100007390697894

and scroll down to the Jan. 10th, this post is not displayed (and a lot too):
https://www.facebook.com/permalink.php?story_fbid=2868730023383326&id=100007390697894

**Comment by cbotsikas** [comment]
The plugin has some logging that should help you and us identify why the post is not shown.
You can see what is hidden by the extension if you open the browser's console and paste and execute the following script as described in [debugging section](https://github.com/tiratatp/facebook_adblock#debugging)
```
document.head.insertAdjacentHTML("beforeend",
`<style>
  *[data-blocked] {
    display:inherit !important;
    border: red 10px solid;
  }
  *[data-blocked=allowedList] {
    border-color: green;
  }
</style>`);
```
Once you have executed this, you should see all posts that the plugin blocks marked with a red border (like in the picture below). In the console, you'll also find some logs like 
`AD Blocked (query='a[role="link"] > span[aria-labelledby]', visibleText='Sponsored') [div]`
If you expand this [div] and hover the nested div (as shown in the picture), you'll be able to identify the blocked post and eventually find the reason it was blocked. 
![image](https://user-images.githubusercontent.com/1640100/105522162-2c8e8e80-5cdd-11eb-8ba2-61be25b803f1.png)

**Comment by cbotsikas** [comment]
@Ricci36 for me, no post is blocked on the profile you posted. I can also see the post from January 10 12:29 PM CET. If you share "AD Blocked" lines from the console, as i described above, we might be able to identify why the posts are blocked for you. Maybe it's related with the language you have on facebook.

**Comment by Ricci36** [comment]
@cbotsikas Funny, today I wanted to look why posts are blocked and ... everything is working fine.
Sorry, seems like this issue can be closed. 
If it will happen again, I will try your way to find it out.

Best regards, Ricci

**Comment by cbotsikas** [comment]
Thank you for the update @Ricci36
