### ISSUE TITLE
Sponsored Posts showing up underneath videos.

### ISSUE THREAD

**Issue by offroadpaparazzi** [tiratatp/facebook_adblock#79]
Sponsored Posts showing up underneath videos.

![sponsored video](https://user-images.githubusercontent.com/60391279/106058440-3dfddf00-60bf-11eb-8744-eb9adfc98e0a.JPG)

I guess its better than mid video ads.

**Comment by tiratatp** [comment]
This is interesting. How do you get to this video? I cannot get to this layout in my Facebook. Is it in `Watch` section (https://www.facebook.com/watch)?

**Comment by HaiDang666** [comment]
I reproduced this issue. The ads show when clicking to open comment section. I'm working on this and make a pull request later.
 
![image](https://user-images.githubusercontent.com/12780733/106460577-24e19d80-64c6-11eb-974a-98c1844a5b64.png)

**Comment by offroadpaparazzi** [comment]
Ahhhh I’m not surprised.

 

It took me a while to get that to happen more than once.

 

You rock!

Thank you

-art

**Comment by HaiDang666** [comment]
It's so rare to happen for me again.

**Comment by offroadpaparazzi** [comment]
Yes, they are very rare.  

 

While looking for them I noticed evry 4th post to be a sponsored one..  (  https://www.facebook.com/watch)

 

 

-art

**Comment by HaiDang666** [comment]
> Yes, they are very rare.  While looking for them I noticed evry 4th post to be a sponsored one..  (  https://www.facebook.com/watch)
> […](#)
> -art From: Hoàng Hồ Hải Đăng <notifications@github.com> Reply-To: tiratatp/facebook_adblock <reply@reply.github.com> Date: Wednesday, February 3, 2021 at 4:05 AM To: tiratatp/facebook_adblock <facebook_adblock@noreply.github.com> Cc: "arthurpepin@comcast.net" <arthurpepin@comcast.net>, Author <author@noreply.github.com> Subject: Re: [tiratatp/facebook_adblock] Sponsored Posts showing up underneath videos. (#79) It's so rare to happen for me again. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I fixed it in this [pull request](https://github.com/tiratatp/facebook_adblock/pull/82)

**Comment by tiratatp** [comment]
Nice @HaiDang666!

**Comment by tiratatp** [comment]
Fixed in 1.9.1

**Comment by tiratatp** [comment]
Version 1.9.0 is still in review for Chrome so we cannot do anything including publish 1.9.1 until 1.9.0 passes the review.

It could take up to 3 weeks to review each version for Chrome. It has only been one week.

**Comment by offroadpaparazzi** [comment]
Thank you very much!

 

-art

**Comment by tiratatp** [comment]
1.9.2 was published
