### ISSUE TITLE
PI-HOLE

### ISSUE THREAD

**Issue by DFlexy** [tiratatp/facebook_adblock#85]
Hi u can modifi one other version for work on pi-hole i like ur plugin for chrome more i want install on pi-hole too u can help ?

**Comment by cbotsikas** [comment]
@DFlexy Would you like to explain your request a bit more. What do you mean by installing on pi-hole?
This browser plugin is hiding the ads in the DOM level while the content is rendered in the browser. Pi-hole on the other side is blocking content on the DNS level, meaning that your browser never even gets the ads.
I do not think it can be ported to pi-hole in any way.
