### ISSUE TITLE
Sponsored posts in Facebook.com/watch 

### ISSUE THREAD

**Issue by offroadpaparazzi** [tiratatp/facebook_adblock#90]
Sing sponsored posts ever 3rd post while scrolling for videos.

<img width="1064" alt="Screen Shot 2021-03-24 at 5 38 40 PM" src="https://user-images.githubusercontent.com/60391279/112387528-43933200-8cc8-11eb-929d-de599597b123.png">

<img width="1064" alt="Screen Shot 2021-03-24 at 5 40 32 PM" src="https://user-images.githubusercontent.com/60391279/112387542-4726b900-8cc8-11eb-96ec-801538d429f8.png">

<img width="1064" alt="Screen Shot 2021-03-24 at 5 41 01 PM" src="https://user-images.githubusercontent.com/60391279/112387554-4aba4000-8cc8-11eb-9686-f375a9a2971f.png">

version 1.92

thanks

**Comment by HaiDang666** [comment]
I think they updated DOM, I'm gonna have a look on this.

**Comment by HaiDang666** [comment]
@tiratatp can u check?

**Comment by offroadpaparazzi** [comment]
It appears  to be OK now..

 

 

Thank You for all you do.

 

-art

 

From: Felix ***@***.***>
Reply-To: tiratatp/facebook_adblock ***@***.***>
Date: Thursday, April 1, 2021 at 4:05 AM
To: tiratatp/facebook_adblock ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [tiratatp/facebook_adblock] Sponsored posts in Facebook.com/watch (#90)

 

@tiratatp can u check?

**Comment by offroadpaparazzi** [comment]
Chrome

**Comment by HaiDang666** [comment]
@tiratatp you can close this.

**Comment by offroadpaparazzi** [comment]
thank you all!
